#!/usr/bin/env python3
"""Generate INDEX.md from entry frontmatter. Do not edit INDEX.md by hand."""
import io
import sys
from pathlib import Path

sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8")

ROOT = Path(__file__).resolve().parent.parent
ENTRIES = ROOT / "entries"
RELATIONS = ("convergent", "divergent", "orthogonal")
DOMAINS = ("mathematics", "physics", "philosophy", "methods")
STATUSES = ("read", "skimmed", "to-read")
REQUIRED = ("title", "authors", "domain", "relation", "status", "ref", "added")


def parse_frontmatter(path):
    lines = path.read_text(encoding="utf-8").splitlines()
    if not lines or lines[0].strip() != "---":
        raise ValueError(f"{path.name}: missing frontmatter")
    meta = {}
    for line in lines[1:]:
        if line.strip() == "---":
            break
        if ":" in line:
            key, value = line.split(":", 1)
            meta[key.strip()] = value.strip()
    return meta


def validate(name, meta):
    errors = [f"{name}: missing field '{k}'" for k in REQUIRED if k not in meta]
    if meta.get("relation") and meta["relation"] not in RELATIONS:
        errors.append(f"{name}: relation '{meta['relation']}' not in {RELATIONS}")
    if meta.get("domain") and meta["domain"] not in DOMAINS:
        errors.append(f"{name}: domain '{meta['domain']}' not in {DOMAINS}")
    if meta.get("status") and meta["status"] not in STATUSES:
        errors.append(f"{name}: status '{meta['status']}' not in {STATUSES}")
    return errors


def main():
    entries, errors = [], []
    for path in sorted(ENTRIES.glob("*.md")):
        meta = parse_frontmatter(path)
        errors.extend(validate(path.name, meta))
        meta["file"] = f"entries/{path.name}"
        entries.append(meta)
    if errors:
        print("\n".join(errors))
        sys.exit(1)

    out = ["# Atlas index", "",
           f"{len(entries)} entries. Generated by `scripts/build_index.py`; do not edit by hand.", ""]

    out.append("## By relation")
    for rel in RELATIONS:
        group = [e for e in entries if e["relation"] == rel]
        out.append(f"\n### {rel.capitalize()} ({len(group)})\n")
        for e in sorted(group, key=lambda x: x["title"].lower()):
            out.append(f"- [{e['title']}]({e['file']}) ({e['domain']}) · {e['authors']}")

    out.append("\n## By domain")
    for dom in DOMAINS:
        group = [e for e in entries if e["domain"] == dom]
        if not group:
            continue
        out.append(f"\n### {dom.capitalize()} ({len(group)})\n")
        for e in sorted(group, key=lambda x: x["title"].lower()):
            out.append(f"- [{e['title']}]({e['file']}) · {e['relation']} · {e['authors']}")

    (ROOT / "INDEX.md").write_text("\n".join(out) + "\n", encoding="utf-8")
    print(f"INDEX.md written: {len(entries)} entries, "
          + ", ".join(f"{sum(1 for e in entries if e['relation'] == r)} {r}" for r in RELATIONS))


if __name__ == "__main__":
    main()
